name: Bug Report
description: Report a bug
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please provide the information below to help reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Exact steps to reproduce the behavior
      placeholder: |
        1. Run command: `ascii-art "example"`
        2. Observe output...
        3. Expected vs actual behavior
    validations:
      required: true

  - type: textarea
    id: input
    attributes:
      label: Input Data
      description: Exact input string or file content used
      placeholder: |
        Input string: "Hello World"
        Or file content: [attach file or paste content]
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Output
      description: What you expected to happen
      render: text
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Output
      description: What actually happened (include error messages)
      render: text
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: "go version go1.20.1 linux/amd64"
    validations:
      required: true

  - type: input
    id: ascii-art-version
    attributes:
      label: Ascii-art Version
      description: Output of `ascii-art -version`
      placeholder: "ascii-art v1.0.0"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Screenshots, logs, related issues, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided all required information above
          required: true
        - label: I can reproduce this issue consistently
          required: true