name: Feature Request
description: Request a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please provide details for the feature request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: One-line description of the feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear description of any alternative solutions or features you've considered

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current use case
        - Critical - Cannot use tool without this
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Areas
      description: Which areas would this feature affect?
      options:
        - label: CLI interface
        - label: Banner rendering
        - label: Performance
        - label: Security
        - label: Documentation
        - label: Testing
        - label: Build/Release

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: |
        How would you use this feature?
        What workflow would it enable?

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of the desired behavior
      placeholder: |
        Command examples:
        ascii-art --new-flag "example"
        
        Expected output:
        [show expected behavior]

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Have you considered backward compatibility?
      options:
        - label: This change is backward compatible
        - label: This change may break existing functionality
        - label: This change requires migration guide
        - label: Not sure about compatibility impact

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request
      placeholder: Links to similar features in other tools, mockups, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for similar requests
          required: true
        - label: I have considered the impact on existing users
          required: true
        - label: I understand this may require significant development effort
          required: true